### ISSUE TITLE
Do you have a screenshot or screencast?

### ISSUE THREAD

**Issue by paintdog** [friendly-traceback/friendly_idle#4]
I don't want to install a pig in a poke. (Sorry.)

**Comment by aroberge** [comment]
See https://aroberge.blogspot.com/2022/06/friendly-idle.html which has many screenshots.

The latest version (from this morning) "fixes" the last issue I mentioned in that blog post - redirecting the information to PyShell.

If you try it, I'd be interested in getting your feedback.

**Comment by aroberge** [comment]
Two screenshots have been added to the README.md file. Closing this issue.
